    
language: node_js
node_js:
- '8.10.0'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng build --prod
